boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c lib.h types.h idt.h keyboard.h i8259.h scan_code.h rtc.h \
  x86_desc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h keyboard.h scan_code.h rtc.h paging.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h scan_code.h
lib.o: lib.c lib.h types.h
paging.o: paging.c types.h lib.h paging.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h
scan_code.o: scan_code.c scan_code.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
